#!/bin/bash

# delete old image
rm "$1"_*.jpg

# download updated image
curl -s https://cdn.star.nesdis.noaa.gov/GOES16/ABI/FD/GEOCOLOR/1808x1808.jpg > ~/Downloads/tempEarth.jpg

# save with random extension
# doesn't seem to work if use same file name every time
rnd=$RANDOM
mv ~/Downloads/tempEarth.jpg "$1_$rnd.jpg"

GIO_EXTRA_MODULES="/usr/lib/x86_64-linux-gnu/gio/modules/"
export GIO_EXTRA_MODULES

# set standard and dark theme background
gsettings set org.gnome.desktop.background picture-options 'scaled'
gsettings set org.gnome.desktop.background picture-uri-dark file://"$1_$rnd.jpg"
gsettings set org.gnome.desktop.background picture-uri file://"$1_$rnd.jpg"

